apiVersion: v1
kind: BuildConfig
metadata:
  name: rhel7-custom
spec:
  output:
    to:
      kind: ImageStreamTag
      name: rhel7-custom:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: https://git.example.com/custom/rhel7.git
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: rhel7:latest
        namespace: openshift
    type: Docker
  triggers: []
