apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mysql-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - persistentvolumeclaims
  - secrets
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lab.redhat.com
  resources:
  - mysqls
  - mysqls/status
  - mysqlbackups
  - mysqlbackups/status
  - mysqlrestores
  - mysqlrestores/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
