---
deploy_namespace: "{{ namespace }}"

application_release_params:
  APPLICATION_RELEASE: "{{ application_release }}"
  REGISTRY_URL: "{{ registry_url }}"
  APPLICATION_NAMESPACE: "{{ deploy_namespace }}"
  DB_SVC: "{{ db_svc }}"

application_build_params:
  APPLICATION_SOURCE_REPOSITORY_URL: "{{ application_source_repository_url }}"
  SOURCE_REF: "{{ source_ref }}"
  APPLICATION_NAMESPACE: "{{ deploy_namespace }}"

openshift_cluster_content:
- object: deployment
  content:
  - name: "widget-factory-deploy"
    template: "{{ inventory_dir }}/../templates/deploy.yml"
    params_from_vars: "{{ application_release_params }}"
    namespace: "{{ deploy_namespace }}"
- object: build
  content:
  - name: "widget-factory build"
    template: "{{ inventory_dir }}/../templates/build.yml"
    params_from_vars: "{{ application_build_params }}"
    namespace: "{{ deploy_namespace }}"
