kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: managed-namespace-operator
subjects:
- kind: ServiceAccount
  name: managed-namespace-operator
  namespace: managed-namespace-operator
roleRef:
  kind: ClusterRole
  name: managed-namespace-operator
  apiGroup: rbac.authorization.k8s.io
