apiVersion: apps/v1
kind: Deployment
metadata:
  name: managed-namespace-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: managed-namespace-operator
  template:
    metadata:
      labels:
        name: managed-namespace-operator
    spec:
      serviceAccountName: managed-namespace-operator
      containers:
        - name: ansible
          command:
          - /usr/local/bin/ao-logs
          - /tmp/ansible-operator/runner
          - stdout
          # Replace this with the built image name
          image: "quay.io/gnekic/managed-namespace-operator:v0.0.2"
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
            readOnly: true
        - name: operator
          # Replace this with the built image name
          image: "quay.io/gnekic/managed-namespace-operator:v0.0.2"
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "managed-namespace-operator"
      volumes:
        - name: runner
          emptyDir: {}
