apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/display-name: Node.js
    # Set action to replace so that removed tags will actually be removed
    openshift-provision/action: replace
  name: nodejs
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      description: Build and run Node.js 6 applications on RHEL 7. For more information
        about using this builder image, including OpenShift considerations, see https://github.com/sclorg/s2i-nodejs-container.
      iconClass: icon-nodejs
      openshift.io/display-name: Node.js 6
      openshift.io/provider-display-name: Red Hat, Inc.
      sampleRepo: https://github.com/openshift/nodejs-ex.git
      supports: nodejs:6,nodejs
      tags: builder,nodejs
      version: "6"
    from:
      kind: DockerImage
      name: registry.access.redhat.com/rhscl/nodejs-6-rhel7:latest
    importPolicy:
      scheduled: true
    name: "6"
    referencePolicy:
      type: Source
  - annotations:
      description: Build and run Node.js 8 applications on RHEL 7. For more information
        about using this builder image, including OpenShift considerations, see https://github.com/sclorg/s2i-nodejs-container.
      iconClass: icon-nodejs
      openshift.io/display-name: Node.js 8
      openshift.io/provider-display-name: Red Hat, Inc.
      sampleRepo: https://github.com/openshift/nodejs-ex.git
      supports: nodejs:8,nodejs
      tags: builder,nodejs
      version: "8"
    from:
      kind: DockerImage
      name: registry.access.redhat.com/rhscl/nodejs-8-rhel7:latest
    importPolicy:
      scheduled: true
    name: "8"
    referencePolicy:
      type: Source
  - annotations:
      description: |-
        Build and run Node.js applications on RHEL 7. For more information about using this builder image, including OpenShift considerations, see https://github.com/sclorg/s2i-nodejs-container/blob/master/4/README.md.

        WARNING: By selecting this tag, your application will automatically update to use the latest version of Node.js available on OpenShift, including major versions updates.
      iconClass: icon-nodejs
      openshift.io/display-name: Node.js (Latest)
      openshift.io/provider-display-name: Red Hat, Inc.
      sampleRepo: https://github.com/openshift/nodejs-ex.git
      supports: nodejs
      tags: builder,nodejs
    from:
      kind: ImageStreamTag
      name: "8"
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source
