apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/display-name: RHEL7
  name: rhel7
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      description: Red Hat Enterprise Linux 7
      iconClass: icon-shadowman
      openshift.io/display-name: RHEL 7
      openshift.io/provider-display-name: Red Hat, Inc.
    from:
      kind: DockerImage
      name: registry.access.redhat.com/rhel7:latest
    importPolicy:
      scheduled: true
    name: "latest"
    referencePolicy:
      type: Source
