---
- hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
  - login-creds.yml
  - vars/pipeline-setup.yml
  roles:
  - role: openshift-provision
    openshift_resource_path:
    - resources
    openshift_clusters:
    - projects:
      - name: "{{ app_name }}-build"
        annotations:
          example.com/quota-size: small
        service_accounts:
        - cicd
        resources:
        - app-limitrange-small.yml
        - app-quota.yml.j2
        role_bindings:
        - role: edit
          users:
          - system:serviceaccount:{{ app_name }}-build:cicd

      - name: "{{ app_name }}-dev"
        annotations:
          example.com/quota-size: medium
        process_templates:
        - file: mysql.template.yml
          parameters:
            NAME: "{{ app_name }}"
            DATABASE_NAME: "{{ database_name }}"
            DATABASE_SERVICE_NAME: "{{ database_service_name }}"
        resources:
        - app-limitrange-medium.yml
        - app-quota.yml.j2
        role_bindings:
        - role: edit
          users:
          - system:serviceaccount:{{ app_name }}-build:cicd

      - name: "{{ app_name }}-stage"
        annotations:
          example.com/quota-size: medium
        process_templates:
        - file: mysql.template.yml
          parameters:
            NAME: "{{ app_name }}"
            DATABASE_NAME: "{{ database_name }}"
            DATABASE_SERVICE_NAME: "{{ database_service_name }}"
        resources:
        - app-limitrange-medium.yml
        - app-quota.yml.j2
        role_bindings:
        - role: edit
          users:
          - system:serviceaccount:{{ app_name }}-build:cicd

      - name: "{{ app_name }}-prod"
        annotations:
          example.com/quota-size: large
        process_templates:
        - file: mysql.template.yml
          parameters:
            NAME: "{{ app_name }}"
            DATABASE_NAME: "{{ database_name }}"
            DATABASE_SERVICE_NAME: "{{ database_service_name }}"
        resources:
        - app-limitrange-large.yml
        - app-quota.yml.j2
        role_bindings:
        - role: edit
          users:
          - system:serviceaccount:{{ app_name }}-build:cicd
  tasks:
  - name: Get token for cicd service account
    command: oc sa get-token -n {{ app_name }}-build cicd
    changed_when: false
    check_mode: no
    register: get_cicd_token

  - name: Save cicd service account connection configuration
    copy:
      content: "{{ cicd_creds |to_yaml}}"
      dest: "{{ playbook_dir }}/cicd-creds.yml"
    # Explicitly indicate localhost in case this playbook is adapted to
    # otherwise run remote
    delegate_to: localhost
    vars:
      cicd_creds:
        openshift_connection_server: "{{ openshift_connection_server }}"
        openshift_connection_insecure_skip_tls_verify: "{{ openshift_connection_insecure_skip_tls_verify |default('false')}}"
        openshift_connection_token: "{{ get_cicd_token.stdout }}"
