---
- name: Set OpenShift version facts
  when: >-
    'Client Version' not in oc_version_output
  set_fact:
    openshift_provision_oc_version: >-
      {{ oc_version_output | regex_replace('(.|\s)*oc (\S+)(.|\s)*', '\2') }}
    openshift_provision_openshift_version: >-
      {{ oc_version_output | regex_replace('(.|\s)*openshift (\S+)(.|\s)*', '\2') }}
