---
- name: Get role bindings for project {{ project.name }}
  command: >-
    {{ oc_cmd }} get rolebinding -n {{ project.name }} -o json
  check_mode: false
  changed_when: false
  failed_when: false
  register: get_role_bindings

- name: Handle project role_bindings
  include_tasks: project-role-binding.yml
  with_items: "{{ project.role_bindings | default([]) }}"
  loop_control:
    loop_var: role_binding
  vars:
    current_role_bindings: >-
      {{ get_role_bindings.stdout | from_json }}
    roleref_query: >-
      {% if '/' in role_binding.role -%}
      roleRef.namespace=='{{ role_binding.role.split('/')[0] }}' &&
      roleRef.name=='{{ role_binding.role.split('/')[1] }}'
      {%- else -%}
      roleRef.name=='{{ role_binding.role }}'
      {%- endif %}
    current_role_users_query: >-
      items[?{{ roleref_query }}].subjects[]|[?kind=='User' || kind=='SystemUser'].name
    current_role_users: >
      {{ current_role_bindings
       | json_query(current_role_users_query)
      }}
    current_role_groups_query: >-
      items[?{{ roleref_query }}].subjects[]|[?kind=='Group' || kind=='SystemGroup'].name
    current_role_groups: >
      {{ current_role_bindings | json_query(current_role_groups_query) }}
    current_role_service_accounts_query: >-
      items[?{{ roleref_query }}].subjects[]|[?kind=='ServiceAccount']
    current_role_service_accounts: >
      {{ current_role_bindings
       | json_query(current_role_service_accounts_query)
      }}
