apiVersion: v1
kind: Template
labels:
  template: jenkins-agent-ansible-pipeline
metadata:
  name: jenkins-agent-ansible-pipeline
objects:
- kind: "BuildConfig"
  apiVersion: "v1"
  metadata:
    labels:
      application: "${BUILDER_NAME}-pipeline"
      group: "${APPLICATION_NAME}"
    name: "${BUILDER_NAME}-pipeline"
    namespace: "${APPLICATION_NAMESPACE}"
  spec:
    source:
      type: Git
      git:
        uri: ${APPLICATION_SOURCE_REPOSITORY_URL}
        ref: ${SOURCE_REF}
      contextDir: ${BUILDER_CONTEXT_DIR}
    strategy:
      type: "JenkinsPipeline"
      jenkinsPipelineStrategy:
        jenkinsfilePath: ${PIPELINE_SCRIPT}
        env:
        - name: "APPLICATION_SOURCE_REPOSITORY_URL"
          value: "${APPLICATION_SOURCE_REPOSITORY_URL}"
        - name: "BUILDER_CONTEXT_DIR"
          value: "${BUILDER_CONTEXT_DIR}"
        - name: "SOURCE_REF"
          value: "${SOURCE_REF}"
        - name: "APPLICATION_NAME"
          value: "${APPLICATION_NAME}"
parameters:
- name: APPLICATION_NAME
  value: jenkins-agent-ansible
- name: BUILDER_NAME
  value: jenkins-agent-ansible
- name: APPLICATION_NAMESPACE
  value: widgetfactory
- name: APPLICATION_SOURCE_REPOSITORY_URL
  value: https://github.com/rh-openshift-ansible-better-together/dev-track.git
- name: SOURCE_REF
  required: true
- name: BUILDER_CONTEXT_DIR
  value: jenkins-agent-ansible
- name: PIPELINE_SCRIPT
  value: Jenkinsfile
